- 👋 Hi I'm Nohelia.
- 🤓 Electronics engineering student at Universidad Industrial de Santander.
- 🌱 Currently learning to program and use Github, so don't be so hard with the projects I upload here.
- ☕ Greetings from Colombia.
